public class MathsMethods{
    public static void Math(){
        System.debug(Math.ceil(4.5));
        System.debug(Math.ceil(3.3));
        System.debug(Math.floor(3.5));
        System.debug(Math.floor(4.6));
        System.debug(Math.pow(2, 2));
        System.debug(Math.random());
        System.debug(Math.rint(31));
        System.debug(Math.rint(892573.2879218));
        System.debug(Math.round(2));
        System.debug(Math.roundToLong(2.5));
        System.debug(Math.signum(5));
        System.debug(Math.signum(0.2));
        System.debug(Math.sqrt(16));
        System.debug(Math.min(5, 7));
        System.debug(Math.max(4.5, 5));
        System.debug(Math.abs(-3));
        System.debug(Math.mod(18, 7));


    }
}